<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Clean" Version="7.0.5" />
    <PackageVersion Include="Umbraco.AI" Version="1.10.1" />
    <PackageVersion Include="Umbraco.AI.OpenAI" Version="1.2.0" />
    <PackageVersion Include="Umbraco.Cms" Version="17.4.2" />
    <PackageVersion Include="Umbraco.Cms.DevelopmentMode.Backoffice" Version="[17.0.0,18.0.0)" />
    <PackageVersion Include="Umbraco.Cms.Api.Common" Version="[17.0.0,18.0.0)" />
    <PackageVersion Include="Umbraco.Cms.Api.Management" Version="[17.0.0,18.0.0)" />
    <PackageVersion Include="Umbraco.Cms.Core" Version="[17.0.0,18.0.0)" />
    <PackageVersion Include="Umbraco.Cms.Infrastructure" Version="[17.0.0,18.0.0)" />
    <PackageVersion Include="Umbraco.Cms.Web.Common" Version="[17.0.0,18.0.0)" />
    <PackageVersion Include="Umbraco.Cms.Web.Website" Version="[17.0.0,18.0.0)" />
    <PackageVersion Include="Microsoft.ICU.ICU4C.Runtime" Version="72.1.0.3" />
  </ItemGroup>
</Project>